#  Heart condition classification ¶

## Importing the libraries

In [92]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

## Importing the dataset

In [93]:
dataset = pd.read_csv('profiles2.csv')
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values
X = np.delete(X, 1, axis=1)
X = np.delete(X, 0, axis=1)

## Splitting the dataset into the Training set and Test set

In [94]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 0)

In [95]:
print(X_train)

[[4714 128 6]
 [3079 89 2]
 [3294 77 7]
 ...
 [4976 106 7]
 [7987 60 7]
 [8383 137 5]]


In [96]:
print(y_train)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 1 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0
 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 

In [97]:
print(X_test)

[[9579 40 3]
 [6324 46 4]
 [8038 60 3]
 [7868 71 8]
 [3897 42 8]
 [9853 63 6]
 [8282 106 4]
 [5527 80 2]
 [4880 89 3]
 [7637 83 4]
 [6054 48 2]
 [7152 118 3]
 [6917 74 2]
 [2289 102 4]
 [4236 71 3]
 [8277 97 6]
 [4303 121 3]
 [6157 102 6]
 [7246 148 8]
 [8070 56 6]
 [7377 125 3]
 [6187 149 4]
 [7840 75 2]
 [2750 64 2]
 [2706 68 4]
 [5338 146 6]
 [4262 90 5]
 [3071 126 3]
 [8948 41 2]
 [8941 128 2]
 [2017 68 8]
 [2754 77 4]
 [9755 124 3]
 [3697 60 2]
 [9291 45 3]
 [3587 47 5]
 [4152 95 8]
 [9206 103 3]
 [9172 49 4]
 [9257 66 7]
 [6107 108 5]
 [5226 45 8]
 [6933 48 4]
 [9672 133 4]
 [2761 105 3]
 [9857 102 8]
 [8372 148 4]
 [6883 81 6]
 [9543 64 6]
 [2074 93 8]
 [8967 136 7]
 [6633 148 4]
 [8070 120 7]
 [6294 68 4]
 [9605 122 6]
 [2498 46 6]
 [9442 107 5]
 [6420 75 2]
 [3465 121 3]
 [9375 48 8]
 [9771 99 5]
 [5665 106 6]
 [2458 146 5]
 [9547 59 3]
 [8835 107 2]
 [2326 97 3]
 [4822 102 7]
 [6895 141 6]
 [7392 41 2]
 [2364 64 8]
 [5482 142 2]
 [2867 136 4]
 [4606 83 7]
 [5861 106 2]
 [3593

In [98]:
print(y_test)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0
 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]


## Feature Scaling

In [99]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [100]:
print(X_train)

[[-0.51999273  1.05086207  0.47764067]
 [-1.22644118 -0.14084558 -1.58411761]
 [-1.13354429 -0.50752486  0.99308024]
 ...
 [-0.40678814  0.37861672  0.99308024]
 [ 0.89420041 -1.02698717  0.99308024]
 [ 1.06530353  1.32587152 -0.0377989 ]]


In [101]:
print(X_test)

[[ 1.58206949 -1.6381193  -1.06867804]
 [ 0.17565376 -1.45477966 -0.55323847]
 [ 0.91623642 -1.02698717 -1.06867804]
 [ 0.84278307 -0.6908645   1.50851981]
 [-0.87300091 -1.57700609  1.50851981]
 [ 1.70045901 -0.93531735  0.47764067]
 [ 1.02166359  0.37861672 -0.55323847]
 [-0.16871285 -0.41585504 -1.58411761]
 [-0.44826768 -0.14084558 -1.06867804]
 [ 0.74297292 -0.32418522 -0.55323847]
 [ 0.05899255 -1.39366645 -1.58411761]
 [ 0.53341481  0.745296   -1.06867804]
 [ 0.43187635 -0.59919468 -1.58411761]
 [-1.56778324  0.2563903  -0.55323847]
 [-0.72652628 -0.6908645  -1.06867804]
 [ 1.0195032   0.10360727  0.47764067]
 [-0.69757701  0.83696582 -1.06867804]
 [ 0.10349664  0.2563903   0.47764067]
 [ 0.5740302   1.66199419  1.50851981]
 [ 0.93006294 -1.1492136   0.47764067]
 [ 0.63063249  0.95919225 -1.06867804]
 [ 0.116459    1.6925508  -0.55323847]
 [ 0.83068487 -0.56863807 -1.58411761]
 [-1.36859502 -0.90476074 -1.58411761]
 [-1.38760648 -0.78253432 -0.55323847]
 [-0.2503757   1.60088098

## Training the Logistic Regression model on the Training set

## Training the Logistic Regression model on the Training set

##Training the Random forest classification model ¶

In [102]:
from sklearn.ensemble import RandomForestClassifier
random_classifier =  RandomForestClassifier(n_estimators=10,criterion='entropy',random_state=0)
random_classifier.fit(X_train,y_train)

RandomForestClassifier(criterion='entropy', n_estimators=10, random_state=0)

## Predicting a new result

In [103]:
#print(classifier.predict(sc.transform([[3434, 120, 8]])))

## Predicting the Test set results

In [104]:
#y_pred = classifier.predict(X_test)
#print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

In [ ]:
## Random forest classifier prediction 

In [106]:
print(random_classifier.predict(sc.transform([[1434, 110, 3]])))

[0]


## Making the Confusion Matrix

In [107]:
#from sklearn.metrics import confusion_matrix, accuracy_score
#cm = confusion_matrix(y_test, y_pred_random)
#print(cm)
#accuracy_score(y_test, y_pred)

In [108]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred_random)
print(cm)
accuracy_score(y_test, y_pred_random)

[[241   0]
 [  4   5]]


0.984